# Generated by Django 3.1.4 on 2020-12-11 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table='my_test',
        ),
    ]
