# Generated by Django 3.1.4 on 2020-12-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_auto_20201211_0501'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table=None,
        ),
    ]
