# Generated by Django 3.1.4 on 2020-12-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0003_auto_20201211_0518'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table='howdy_exam',
        ),
    ]
