# Generated by Django 3.1.4 on 2020-12-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0004_auto_20201211_0546'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table=None,
        ),
    ]
