# Generated by Django 3.1.4 on 2020-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0006_auto_20201211_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ShotExam',
        ),
    ]
